### ISSUE TITLE
Boars don't follow.

### ISSUE THREAD

**Issue by RolePlayerVintage** [meldurson/AllTameable#3]
They just give the "boar loves you" blurb without the follow behavior.

**Comment by meldurson** [comment]
The default tamelist do not modify vanilla behaviour of boar to be commandable, you would need to have the Boar line start with Boar,true to make it command able. Does your tamelist start with this?

**Comment by RolePlayerVintage** [comment]
XD Sorry lol. I didn't fully read through the files. Should've been able to figure this one out without bugging you.
